language: python
env:
  global:
  - COGNITO_DOMAIN="https://taxiapp.auth.us-east-1.amazoncognito.com"
  - COGNITO_USER_POOL_ID="us-east-1_xjtJDp8bd"
  - COGNITO_APP_CLIENT_ID="4534h0um83kap0o29gqt5heids"
  - COGNITO_AWS_REGION="us-east-1"
  - COGNITO_APP_CLIENT_SECRET="194t8b57d9uikl7f19pnih83vn8l2i19mhkm5rpjes5irnthrtuk"
  - SECRET_KEY:
    - secure: MtxqW9rTIMGG+i9dPCsl5s3EJrmCIIegRHVkWkazaLjZ7H1BrAjAT2Ewfwj+RyBzoyYQYlFjeonIdOtY/OMLVexngigBM1lfe87ridQtt8jKazJjOxtAhTse3nKaap0+MD2pHCADpxjiwOmzv3CSYZKLUSVIMZ9zHoQLVAV3kI9en125Oy8hoovBNUKOmAGcja2tSnHqGoIkFkHuVv+mhrTMnDtWEWm/VNWtsxPaZyDmZm2XJmKNCzdxLJ8YUY77pP9Amwl49tLBPRLe5TP0PU3hYRWCl3574ZT5hIHftotqXKhpxSgCG07tZTF7cUuZTwc244LNzu2key4KV300Td1EVceVnrdJqvI8KaE1tcbmBzK4qhabR8tkVkv2OuIw9mn4llu3zwmHxsQ6Xyo4R+3hLnT7Zvc3dEAj6cw4xIwiNdPn/3bl6df23KgQ/3k38h70p9WIXJnYC3eDldzIuvaXalyLVVyNTgbyV/TDNToh8ZRewVmZ9lsp69iV0MfyJLUdOvN1MFsXPPh12LPs83wqrpTWxuUovI7L6Lv6ee6wHPK+QIM9PzYonwwA22XYrvn8PIfhbtMLxi9+SeaVC5HlbWYPdVzQFFpOYeHugL5T36BKKMkxPUu5J1Y0c3SeKcFPSjG9Rbq6XBnupzvAQ/rea4jKcCEtTt1pZ82K6Ik=
  
install:
- cd taxiapp
- pip install -r requirements.txt
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
- coverage run --source=taxiapp manage.py test
- coverage report
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA6ASHD2VT2VLIVJUW
  secret_access_key: "$AWS_SECRET_KEY"
  region: us-east-1
  app: taxiapp
  env:
  - SECRET_KEY:
    - secure: MtxqW9rTIMGG+i9dPCsl5s3EJrmCIIegRHVkWkazaLjZ7H1BrAjAT2Ewfwj+RyBzoyYQYlFjeonIdOtY/OMLVexngigBM1lfe87ridQtt8jKazJjOxtAhTse3nKaap0+MD2pHCADpxjiwOmzv3CSYZKLUSVIMZ9zHoQLVAV3kI9en125Oy8hoovBNUKOmAGcja2tSnHqGoIkFkHuVv+mhrTMnDtWEWm/VNWtsxPaZyDmZm2XJmKNCzdxLJ8YUY77pP9Amwl49tLBPRLe5TP0PU3hYRWCl3574ZT5hIHftotqXKhpxSgCG07tZTF7cUuZTwc244LNzu2key4KV300Td1EVceVnrdJqvI8KaE1tcbmBzK4qhabR8tkVkv2OuIw9mn4llu3zwmHxsQ6Xyo4R+3hLnT7Zvc3dEAj6cw4xIwiNdPn/3bl6df23KgQ/3k38h70p9WIXJnYC3eDldzIuvaXalyLVVyNTgbyV/TDNToh8ZRewVmZ9lsp69iV0MfyJLUdOvN1MFsXPPh12LPs83wqrpTWxuUovI7L6Lv6ee6wHPK+QIM9PzYonwwA22XYrvn8PIfhbtMLxi9+SeaVC5HlbWYPdVzQFFpOYeHugL5T36BKKMkxPUu5J1Y0c3SeKcFPSjG9Rbq6XBnupzvAQ/rea4jKcCEtTt1pZ82K6Ik=
  - COGNITO_DOMAIN="https://taxiapp.auth.us-east-1.amazoncognito.com"
  - COGNITO_USER_POOL_ID="us-east-1_xjtJDp8bd"
  - COGNITO_APP_CLIENT_ID="4534h0um83kap0o29gqt5heids"
  - COGNITO_AWS_REGION="us-east-1"
  - COGNITO_APP_CLIENT_SECRET="194t8b57d9uikl7f19pnih83vn8l2i19mhkm5rpjes5irnthrtuk"
  bucket_name: elasticbeanstalk-us-east-1-963295565159
  on:
    repo: gcivil-nyu-org/INET-Wednesday-Spring2024-Team-3
    branch:
    - master
    - testbranch
  skip_cleanup: 'true'
