language: python
python:
  - "3.9"
env:
  global:
    - SECRET_KEY = $SECRET_KEY
install:
  - cd taxiapp
  - python3 -m pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - flake8 .
  - coverage run --source=taxiapp manage.py test
  - coverage report
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: taxi2
  env: taxi2-env
  bucket_name: elasticbeanstalk-us-east-1-761018855731
  on:
    repo: devmcdonald/Software-Engineering
    branch:
      - master
  cleanup: 'false'

