branch-defaults:
  test-branch:
    environment: taxiapp-dev
environment-defaults:
  taxiapp-dev:
    branch: null
    repository: null
global:
  application_name: taxiapp
  default_ec2_keyname: taxi-keypair
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
